categories = {
    "speech": "💬",
    "thought": "💭",
    "sleep": "💤",
    "clock": "🕑",
    "cards": "🃏",
    "speaker": "🔊",
    "loudspeaker": "📢",
    "megaphone": "📣",
    "music": "🎵",
    "atm": "🏧",
    "restroom": "🚻",
    "race": "🏁",
    "bomb": "💣",
    "bath": "🛀",
    "bed": "🛌",
    "knife": "🔪",
    "map": "🗺️",
    "compass": "🧭",
    "brick": "🧱",
    "oil": "🛢️",
    "bell": "🛎️",
    "luggage": "🧳",
    "hourglass": "⏳",
    "watch": "⌚",
    "alarm clock": "⏰",
    "stopwatch": "⏱️",
    "timer": "⏲️",
    "thermometer": "🌡️",
    "firecracker": "🧨",
    "balloon": "🎈",
    "party popper": "🎉",
    "confetti": "🎊",
    "ribbon": "🎀",
    "gift": "🎁",
    "diving mask": "🤿",
    "yo-yo": "🪀",
    "kite": "🪁",
    "crystal ball": "🔮",
    "joystick": "🕹️",
    "teddy bear": "🧸",
    "picture": "🖼️",
    "shopping bags": "🛍️",
    "gem stone": "💎",
    "radio": "📻",
    "banjo": "🪕",
    "mobile phone": "📱",
    "smartphone": "📱",
    "iphone": "📱",
    "pager": "📟",
    "fax": "📠",
    "battery": "🔋",
    "electric plug": "🔌",
    "laptop": "💻",
    "macbook": "💻",
    "desktop computer": "🖥️",
    "computer": "🖥️",
    "mac": "🖥️",
    "pc": "🖥️",
    "printer": "🖨️",
    "computer mouse": "🖱️",
    "trackball": "🖲️",
    "floppy disk": "💾",
    "cd": "💿",
    "dvd": "📀",
    "movie camera": "🎥",
    "television": "📺",
    "camera": "📷",
    "video camera": "📹",
    "magnifying glass": "🔎",
    "candle": "🕯️",
    "light bulb": "💡",
    "flashlight": "🔦",
    "lantern": "🏮",
    "book": "📖",
    "books": "📚",
    "notebook": "📓",
    "ledger": "📒",
    "newspaper": "📰",
    "money": "💰",
    "credit card": "💳",
    "receipt": "🧾",
    "package": "📦",
    "pen": "🖊️",
    "paintbrush": "🖌️",
    "crayon": "🖍️",
    "file folder": "📁",
    "calendar": "📅",
    "notepad": "🗒️",
    "stocks": "📈",
    "chart": "📉",
    "pushpin": "📌",
    "paperclip": "📎",
    "ruler": "📐",
    "scissors": "✂️️",
    "wastebasket": "🗑️",
    "bin": "🗑️",
    "lock": "🔒",
    "key": "🔑",
    "hammer": "🔨",
    "axe": "🪓",
    "pick": "⛏️",
    "dagger": "🗡️",
    "sword": "⚔️️",
    "pistol": "🔫",
    "shield": "🛡️",
    "wrench": "🔧",
    "nut": "🔩",
    "bolt": "🔩",
    "gear": "⚙️️",
    "clamp": "🗜️",
    "scale": "⚖️️",
    "chains": "⛓️",
    "toolbox": "🧰",
    "magnet": "🧲",
    "test tube": "🧪",
    "microscope": "🔬",
    "telescope": "🔭",
    "antenna": "📡",
    "syringe": "💉",
    "bandage": "🩹",
    "stethoscope": "🩺",
    "door": "🚪",
    "chair": "🪑",
    "toilet": "🚽",
    "bathtub": "🛁",
    "razor": "🪒",
    "lotion": "🧴",
    "safety pin": "🧷",
    "broom": "🧹",
    "basket": "🧺",
    "toilet paper": "🧻",
    "fire extinguisher": "🧯",
    "shopping cart": "🛒",
    "cigarette": "🚬",
    "climbing": "🧗",
    "fencing": "🤺",
    "horse racing": "🏇",
    "skiing": "⛷️",
    "snowboarding": "🏂",
    "golf": "🏌️",
    "surfing": "🏄",
    "rowing": "🚣",
    "swimming": "🏊",
    "weight lifting": "🏋️",
    "gym": "🏋️",
    "biking": "🚴",
    "wrestling": "🤼",
    "water polo": "🤽",
    "handball": "🤾",
    "juggling": "🤹",
    "circus": "🎪",
    "skateboard": "🛹",
    "canoe": "🛶",
    "ticket": "🎫",
    "trophy": "🏆",
    "medal": "🏅",
    "soccer": "⚽",
    "soccer ball": "⚽",
    "football": "⚽",
    "baseball": "⚾",
    "softball": "🥎",
    "basketball": "🏀",
    "volleyball": "🏐",
    "american football": "🏈",
    "rugby": "🏉",
    "tennis": "🎾",
    "flying disc": "🥏",
    "bowling": "🎳",
    "cricket sport": "🏏",
    "field hockey": "🏑",
    "ice hockey": "🏒",
    "lacrosse": "🥍",
    "ping pong": "🏓",
    "badminton": "🏸",
    "boxing glove": "🥊",
    "martial arts uniform": "🥋",
    "ice skate": "⛸️",
    "fishing pole": "🎣",
    "running shirt": "🎽",
    "skis": "🎿",
    "sled": "🛷",
    "curling stone": "🥌",
    "pool": "🎱",
    "billiard": "🎱",
    "video game": "🎮",
    "slot machine": "🎰",
    "board game": "🎲",
    "puzzle": "🧩",
    "chess": "♟️",
    "theatre": "🎭",
    "palette": "🎨",
    "painting": "🎨",
    "art": "🎨",
    "microphone": "🎤",
    "saxophone": "🎷",
    "guitar": "🎸",
    "piano": "🎹",
    "trumpet": "🎺",
    "violin": "🎻",
    "drum": "🥁",
    "movie": "🎬",
    "bow and arrow": "🏹",
    "mountain": "⛰️",
    "volcano": "🌋",
    "camping": "🏕️",
    "beach": "🏖️",
    "desert": "🏜️",
    "island": "🏝️",
    "national park": "🏞️",
    "stadium": "🏟️",
    "sightseeing": "🏛️",
    "building construction": "🏗️",
    "house": "🏠",
    "office": "🏢",
    "post office": "🏤",
    "hospital": "🏥",
    "bank": "🏦",
    "hotel": "🏨",
    "convenience store": "🏪",
    "school": "🏫",
    "department store": "🏬",
    "factory": "🏭",
    "castle": "🏰",
    "wedding": "💒",
    "tower": "🗼",
    "statue": "🗽",
    "church": "⛪",
    "fountain": "⛲",
    "tent": "⛺",
    "postcard": "🌇",
    "carousel": "🎠",
    "ferris wheel": "🎡",
    "roller coaster": "🎢",
    "locomotive": "🚂",
    "railway car": "🚃",
    "train": "🚆",
    "metro": "🚇",
    "monorail": "🚝",
    "tram": "🚋",
    "bus": "🚌",
    "trolleybus": "🚎",
    "minibus": "🚐",
    "ambulance": "🚑",
    "fire engine": "🚒",
    "police": "🚓",
    "taxi": "🚕",
    "automobile": "🚗",
    "car": "🚗",
    "truck": "🚚",
    "tractor": "🚜",
    "racing car": "🏎️",
    "motorcycle": "🏍️",
    "motor scooter": "🛵",
    "bicycle": "🚲",
    "kick scooter": "🛴",
    "fuel": "⛽",
    "anchor": "⚓",
    "ferry": "⛴️",
    "boat": "🛥️",
    "ship": "🚢",
    "airplane": "✈️",
    "parachute": "🪂",
    "seat": "💺",
    "helicopter": "🚁",
    "cableway": "🚠",
    "satellite": "🛰️",
    "rocket": "🚀",
    "flying saucer": "🛸",
    "planet": "🪐",
    "parasol": "⛱️",
    "fireworks": "🎆",
    "banknote": "💵",
    "cash": "💵",
    "glasses": "👓",
    "goggles": "🥽",
    "lab coat": "🥼",
    "safety vest": "🦺",
    "necktie": "👔",
    "t-shirt": "👕",
    "scarf": "🧣",
    "gloves": "🧤",
    "socks": "🧦",
    "kimono": "👘",
    "sari": "🥻",
    "briefs": "🩲",
    "shorts": "🩳",
    "bikini": "👙",
    "woman’s clothes": "👚",
    "purse": "👛",
    "clutch bag": "👝",
    "backpack": "🎒",
    "man’s shoe": "👞",
    "running shoe": "👟",
    "hiking boot": "🥾",
    "flat shoe": "🥿",
    "high-heeled shoe": "👠",
    "woman’s sandal": "👡",
    "ballet shoes": "🩰",
    "woman’s boot": "👢",
    "crown": "👑",
    "woman’s hat": "👒",
    "top hat": "🎩",
    "graduation cap": "🎓",
    "billed cap": "🧢",
    "briefcase": "💼",
    "nail polish": "💅",
    "cosmetics": "💅",
    "makeup": "💅",
    "helmet": "⛑️",
    "thread": "🧵",
    "yarn": "🧶",
    "bouquet": "💐",
    "rose": "🌹",
    "hibiscus": "🌺",
    "sunflower": "🌻",
    "tulip": "🌷",
    "seeds": "🌱",
    "cactus": "🌵",
    "christmas tree": "🎄",
    "evergreen tree": "🌲",
    "deciduous tree": "🌳",
    "palm tree": "🌴",
    "herb": "🌿",
    "shamrock": "☘️",
    "lipstick": "💄",
    "maple syrup": "🍁",
    "maple": "🍁",
    "grapes": "🍇",
    "melon": "🍈",
    "watermelon": "🍉",
    "tangerine": "🍊",
    "lemon": "🍋",
    "banana": "🍌",
    "pineapple": "🍍",
    "mango": "🥭",
    "red apple": "🍎",
    "green apple": "🍏",
    "fruit": "🍏",
    "pear": "🍐",
    "peach": "🍑",
    "cherries": "🍒",
    "strawberry": "🍓",
    "kiwi fruit": "🥝",
    "tomato": "🍅",
    "coconut": "🥥",
    "avocado": "🥑",
    "eggplant": "🍆",
    "potato": "🥔",
    "carrot": "🥕",
    "corn": "🌽",
    "hot pepper": "🌶️",
    "cucumber": "🥒",
    "lettuce": "🥬",
    "broccoli": "🥦",
    "garlic": "🧄",
    "onion": "🧅",
    "mushroom": "🍄",
    "peanuts": "🥜",
    "chestnut": "🌰",
    "bread": "🍞",
    "croissant": "🥐",
    "baguette bread": "🥖",
    "pretzel": "🥨",
    "bagel": "🥯",
    "pancakes": "🥞",
    "waffle": "🧇",
    "cheese": "🧀",
    "meat on bone": "🍖",
    "poultry leg": "🍗",
    "bacon": "🥓",
    "food": "🍔",
    "hamburger": "🍔",
    "french fries": "🍟",
    "pizza": "🍕",
    "hot dog": "🌭",
    "sandwich": "🥪",
    "taco": "🌮",
    "burrito": "🌯",
    "falafel": "🧆",
    "egg": "🥚",
    "green salad": "🥗",
    "vegetarian": "🥗",
    "vegetable": "🥗",
    "popcorn": "🍿",
    "butter": "🧈",
    "salt": "🧂",
    "can": "🥫",
    "rice": "🍚",
    "spaghetti": "🍝",
    "sweet potato": "🍠",
    "sushi": "🍣",
    "fried shrimp": "🍤",
    "dumpling": "🥟",
    "fortune cookie": "🥠",
    "noodle": "🥡",
    "oyster": "🦪",
    "seafood": "🦪",
    "ice cream": "🍦",
    "doughnut": "🍩",
    "cookie": "🍪",
    "birthday cake": "🎂",
    "shortcake": "🍰",
    "cupcake": "🧁",
    "pie": "🥧",
    "chocolate bar": "🍫",
    "candy": "🍬",
    "lollipop": "🍭",
    "custard": "🍮",
    "honey pot": "🍯",
    "baby bottle": "🍼",
    "milk": "🥛",
    "yoghurt": "🥛",
    "hot beverage": "☕",
    "teacup": "🍵",
    "soup": "🍵",
    "sake": "🍶",
    "champagne": "🍾",
    "wine": "🍷",
    "cocktail": "🍸",
    "tropical drink": "🍹",
    "beer": "🍺",
    "whiskey": "🥃",
    "smoothie": "🥤",
    "juice": "🧃",
    "cold beverage": "🚰",
    "mate": "🧉",
    "ice": "🧊",
    "chopsticks": "🥢",
    "plate": "🍽️",
    "fork and knife": "🍴",
    "spoon": "🥄",
    "monkey": "🐵",
    "gorilla": "🦍",
    "orangutan": "🦧",
    "dog": "🐶",
    "poodle": "🐩",
    "wolf": "🐺",
    "fox": "🦊",
    "lion": "🦁",
    "tiger": "🐅",
    "leopard": "🐆",
    "unicorn": "🦄",
    "zebra": "🦓",
    "raccoon": "🦝",
    "cat": "🐈",
    "venison": "🦌",
    "game": "🦌",
    "deer": "🦌",
    "boar": "🐗",
    "pig": "🐖",
    "pork": "🐖",
    "ox": "🐂",
    "buffalo": "🐃",
    "cow": "🐮",
    "beef": "🐮",
    "goat": "🐐",
    "ram": "🐏",
    "ewe": "🐑",
    "lamb": "🐑",
    "camel": "🐫",
    "llama": "🦙",
    "giraffe": "🦒",
    "elephant": "🐘",
    "rhinoceros": "🦏",
    "hippopotamus": "🦛",
    "mouse": "🐁",
    "rat": "🐀",
    "hamster": "🐹",
    "rabbit": "🐇",
    "chipmunk": "🐿️",
    "hedgehog": "🦔",
    "bat": "🦇",
    "bear": "🐻",
    "koala": "🐨",
    "panda": "🐼",
    "sloth": "🦥",
    "otter": "🦦",
    "skunk": "🦨",
    "kangaroo": "🦘",
    "badger": "🦡",
    "turkey": "🦃",
    "chicken": "🐔",
    "hatching": "🐣",
    "penguin": "🐧",
    "dove": "🕊️",
    "eagle": "🦅",
    "duck": "🦆",
    "swan": "🦢",
    "owl": "🦉",
    "octopus": "🐙",
    "snail": "🐌",
    "cricket": "🦗",
    "spider": "🕷️",
    "scorpion": "🦂",
    "mosquito": "🦟",
    "crab": "🦀",
    "lobster": "🦞",
    "shrimp": "🦐",
    "squid": "🦑",
    "flamingo": "🦩",
    "peacock": "🦚",
    "frog": "🐸",
    "crocodile": "🐊",
    "turtle": "🐢",
    "lizard": "🦎",
    "snake": "🐍",
    "dragon": "🐉",
    "sauropod": "🦕",
    "t-rex": "🦖",
    "spouting whale": "🐳",
    "whale": "🐋",
    "dolphin": "🐬",
    "fish": "🐟",
    "tropical fish": "🐠",
    "blowfish": "🐡",
    "shark": "🦈",
    "spiral shell": "🐚",
    "butterfly": "🦋",
    "bug": "🐛",
    "ant": "🐜",
    "honeybee": "🐝",
    "lady beetle": "🐞",
    "hot": "🥵",
    "cold": "🥶",
    "exploding": "🤯",
    "cowboy": "🤠",
    "party": "🥳",
    "skull": "☠️",
    "clown": "🤡",
    "ghost": "👻",
    "alien": "👽",
    "monster": "👾",
    "robot": "🤖",
    "kiss": "💋",
    "selfie": "🤳",
    "hearing aid": "🦻",
    "brain": "🧠",
    "leg": "🦵",
    "foot": "🦶",
    "ear": "👂",
    "nose": "👃",
    "biceps": "💪",
    "tooth": "🦷",
    "bone": "🦴",
    "eyes": "👀",
    "eye": "👁️",
    "tongue": "👅",
    "mouth": "👄",
    "student": "🧑‍🎓",
    "superhero": "🦸",
    "teacher": "👨‍🏫",
    "farmer": "👨‍🌾",
    "cook": "👨‍🍳",
    "mechanic": "👨‍🔧",
    "office worker": "👨‍💼",
    "scientist": "👩‍🔬",
    "technologist": "👨‍💻",
    "singer": "👩‍🎤",
    "artist": "👩‍🎨",
    "astronaut": "👨‍🚀",
    "firefighter": "👨‍🚒",
    "police officer": "👮",
    "detective": "🕵️",
    "guard": "💂",
    "construction worker": "👷",
    "prince": "🤴",
    "princess": "👸",
    "bride": "👰",
    "groom": "🤵",
    "santa claus": "🎅",
    "baby angel": "👼",
    "supervillain": "🦹",
    "mage": "🧙",
    "fairy": "🧚",
    "vampire": "🧛",
    "mermaid": "🧜",
    "elf": "🧝",
    "genie": "🧞",
    "zombie": "🧟",
    "massage": "💆",
    "haircut": "💇‍️",
    "walking": "🚶",
    "wheelchair": "👨‍🦽",
    "running": "🏃",
    "dancing": "💃",
    "sauna": "🧖",
    "meditation": "🧘",
    "yoga": "🧘",
    "family": "👪",
    "blood": "🩸",
    "globe": "🌍",
    "world": "🌍",
    "moon": "🌔",
    "sun": "☀️️",
    "star": "⭐",
    "cloud": "☁️️",
    "rainbow": "🌈",
    "tornado": "🌪️",
    "fog": "🌫️",
    "wind": "🌬️",
    "air": "🌬️",
    "air condition": "💨",
    "electricity": "⚡",
    "snowflake": "❄️️",
    "snowman": "☃️️",
    "comet": "☄️️",
    "fire": "🔥",
    "droplet": "💧",
    "sparkles": "✨",
    "coffee": "☕",
    "tea": "🍵",
    "shirt": "👕",
    "jeans": "👖",
    "shoes": "👟",
    "swimsuit": "🩱",
    "coat": "🧥",
    "dress": "👗",
    "handbag": "👜",
    "hat": "👒",
    "jewelry": "💍",
    "ring": "💍",
    "umbrella": "☂️",
    "sunglasses": "🕶",
    "toy": "🧸",
    "gps": "🛰",
    "paper": "📄",
    "pencil": "✏️",
    "flowers": "🌸",
    "soap": "🧼",
    "sponge": "🧽",
    "cleaning": "🧴",
    "shower": "🚿",
    "pill": "💊",
    "drug": "💊",
    "toothbrush": "🦷",
    "meat": "🥩",
    "snack": "🥨",
    "cake": "🍰",
    "bowl": "🥣",
    "cutlery": "🍴",
    "pet": "🐾",
    "horse": "🐎",
    "reptile": "🐍",
    "bird": "🦜",
    "parrot": "🦜",
    "budgie": "🦜",
}
