name: react-native-android-build-apk
on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          npm install

      - name: Build Android Release
        run: |
          cd android && chmod +x ./gradlew && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
  build-windows:
    needs: install-and-test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          npm install

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Nuget Restore
        run: cd windows && nuget restore bachelors_thesis_accounting_ocr.sln

      - name: Build Windows Release
        run: |
          cd windows && msbuild bachelors_thesis_accounting_ocr.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: bachelors_thesis_accounting_ocr.exe
          path: windows/x64/Release/bachelors_thesis_accounting_ocr
