name: CI
on:
  push:
    branches:
      - master
jobs:
  lint-and-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          npm install

      - name: check formatting
        run: |
          npm run prettier:check
#          TODO lint and test

  visual-regression:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install npm dependencies
        run: |
          npm install
      - name: Workaround for detached HEAD
        run: |
          git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull
      - name: Capture Screenshots
        run: |
          npm run storycap:web
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Run visual-regression test
        run: |
          npm run reg-suit:web:ci

#  build-android:
#    timeout-minutes: 10
#    needs: lint-and-test
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Install npm dependencies
#        run: |
#          npm install
#
#      - name: Install NDK
#        run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}
#
#      - name: Build Android Release
#        run: |
#          cd android && chmod +x ./gradlew && ./gradlew assembleRelease
#
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v1
#        with:
#          name: app-release.apk
#          path: android/app/build/outputs/apk/release/

#  build-windows:
#    timeout-minutes: 10
#    needs: lint-and-test
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Install npm dependencies
#        run: |
#          npm install
#
#      - name: Build Windows Release
#        run: |
#          npx react-native run-windows --release --arch x64
#
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v1
#        with:
#          name: bachelors_thesis_accounting_ocr_windows
#          path: windows/x64/Release/bachelors_thesis_accounting_ocr/
