name: Python API deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'Install Newman dependency'
        run: npm i --prefix python-api/tests/

      - name: 'Run Postman tests'
        run: |
          cd python-api/tests/
          sleep 1200
          npm run test
